// GENERATED from docs/handoffs/10-content-pack.md — do not edit by hand.
//
// Handoff 10's signed member content (review STEADY-CLINREV-2026-09-24-10,
// src/lib/content-approval.ts). The pack says "transcribe text exactly. If a
// string must change for layout, flag it for re-review rather than
// rewording", so every string below is lifted from the pack by a script, and
// tests/content-approval.test.ts fails if any is not in the pack word for word.
// A change to the words is a change to the pack and a new review.

import { AccessTier } from "../safety/types";
import type { Practice } from "../practices";
import type { Lesson } from "../lessons";

/** 1A: the skills library (rows A02 selection and gating, A03 wording, A05
 *  skip-if notes). Gating is the pack's, which matches every source entry in
 *  the knowledge base. None uses imagery. */
export const H10_SKILLS: Practice[] = [
  {
    id: "skill-orient-room", type: "skill", title: "Find the room",
    intro: "A quick way to remind your body where you are and when it is.",
    whenToUse: "When you feel pulled away from the present, or the room feels far off.",
    durationSec: 120, intensity: 1, tags: ["S01"], hasHold: false,
    minTier: AccessTier.GROUNDING_ONLY, maxActivation: 10, imagery: false,
    sourceTechniqueId: "somatic-orientation",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Keep your eyes open. Let them move slowly around the room." },
      { text: "Name five things you can see. Take your time with each one." },
      { text: "Name four things you can hear, near or far." },
      { text: "Notice three places your body is touching something: feet, seat, back." },
      { text: "Name two things you can smell, or two things you like the look of." },
      { text: "Say one true thing about right now: where you are, and today's day." },
    ],
  },
  {
    id: "skill-contact-points", type: "skill", title: "What's holding you up",
    intro: "Feeling what supports your body can bring a sense of steadiness.",
    whenToUse: "When you feel shaky, unsteady, or like you're floating.",
    durationSec: 120, intensity: 1, tags: ["S02"], hasHold: false,
    minTier: AccessTier.GROUNDING_ONLY, maxActivation: 9, imagery: false,
    sourceTechniqueId: "somatic-contact-points",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Sit or stand wherever you are. No need to move." },
      { text: "Press your feet into the floor. Notice the floor pressing back." },
      { text: "Notice the seat under you, or the wall or bed if you're leaning." },
      { text: "Let your hands rest on something solid: your legs, a table, the arms of a chair." },
      { text: "For a few breaths, just notice: you are being held up right now." },
    ],
  },
  {
    id: "skill-comfort-temperature", type: "skill", title: "A comfortable warmth",
    intro: "A gentle temperature sensation gives your attention somewhere to land.",
    whenToUse: "When your body feels numb or far away.",
    skipIf: ["Anything that feels too hot or too cold. Comfort is the point, never discomfort."],
    durationSec: 120, intensity: 1, tags: ["S03"], hasHold: false,
    minTier: AccessTier.GROUNDING_ONLY, maxActivation: 9, imagery: false,
    sourceTechniqueId: "somatic-temperature-anchor",
    signoffRowIds: ["CV10_A02", "CV10_A03", "CV10_A05"],
    steps: [
      { text: "Find something comfortably warm or cool: a warm mug, a soft blanket, water running over your hands at a temperature you like." },
      { text: "Hold it, or let it rest against your hands." },
      { text: "Notice exactly where you feel the temperature." },
      { text: "Notice whether it changes as you stay with it." },
      { text: "When you're ready, set it down and look around the room." },
    ],
  },
  {
    id: "skill-move-it-out", type: "skill", title: "Move it out",
    intro: "A short burst of movement can use up some of the energy that builds with strong feelings.",
    whenToUse: "When you feel keyed up, restless, or about to boil over.",
    skipIf: ["You have a heart condition, an injury, or a reason to avoid exertion. Try \"What's holding you up\" instead."],
    durationSec: 180, intensity: 2, tags: ["S04"], hasHold: false,
    minTier: AccessTier.GROUNDING_ONLY, maxActivation: 9, imagery: false,
    sourceTechniqueId: "dbt-tipp-move",
    signoffRowIds: ["CV10_A02", "CV10_A03", "CV10_A05"],
    steps: [
      { text: "Pick something your body can do safely: a brisk walk, marching in place, pushing against a wall." },
      { text: "Do it for about a minute, at an effort that feels strong but okay." },
      { text: "Stop. Stand or sit and let your breathing settle on its own." },
      { text: "Notice what's different in your body now, even a little." },
      { text: "Repeat once more only if you want to." },
    ],
  },
  {
    id: "skill-stop", type: "skill", title: "Pause before reacting",
    intro: "A four-step pause for the moment before you act on a strong feeling.",
    whenToUse: "When you feel the pull to say or do something fast.",
    durationSec: 60, intensity: 1, tags: ["S05"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 7, imagery: false,
    sourceTechniqueId: "dbt-stop-skill",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Stop. Freeze for a moment. Don't act yet." },
      { text: "Take a step back, even just one slow breath out." },
      { text: "Look around. What's actually happening right now? What do you notice?" },
      { text: "Choose your next move. What would help this situation, and you, most?" },
    ],
  },
  {
    id: "skill-soothe-senses", type: "skill", title: "Soothe with your senses",
    intro: "Small comforts through sight, sound, smell, taste, and touch.",
    whenToUse: "When you're upset and want something gentle to lean on.",
    durationSec: 180, intensity: 1, tags: ["S06"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 7, imagery: false,
    sourceTechniqueId: "dbt-self-soothe",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Pick one sense to start with." },
      { text: "Sight: look at something you find calming or pleasant." },
      { text: "Sound: put on a sound you like, or listen to the quietest sound in the room." },
      { text: "Smell or taste: something familiar and comforting, like tea, soap, or a piece of fruit." },
      { text: "Touch: something soft, smooth, or weighted." },
      { text: "Stay with whichever one helps most, for as long as you like." },
    ],
  },
  {
    id: "skill-worry-later", type: "skill", title: "Worry later",
    intro: "Giving worries a set time can make them easier to set down now.",
    whenToUse: "When the same worries keep circling.",
    durationSec: 120, intensity: 1, tags: ["S07"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 6, imagery: false,
    sourceTechniqueId: "cbt-worry-window",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Write the worry down in a few words, or say it to yourself." },
      { text: "Pick a 15-minute window later today for worrying. Not close to bedtime." },
      { text: "When the worry comes back before then, remind yourself: \"That's for later.\"" },
      { text: "Turn your attention to what you're doing right now." },
      { text: "At the worry time, look at the list. Some worries may feel smaller by then. It's fine if they don't." },
    ],
  },
  {
    id: "skill-make-room", type: "skill", title: "Make a little room",
    intro: "Instead of fighting a feeling, giving it some space can soften it.",
    whenToUse: "When a feeling is uncomfortable but manageable.",
    skipIf: ["The feeling is very strong right now. Try \"Find the room\" first."],
    durationSec: 180, intensity: 1, tags: ["S08"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 6, imagery: false,
    sourceTechniqueId: "act-expansion",
    signoffRowIds: ["CV10_A02", "CV10_A03", "CV10_A05"],
    steps: [
      { text: "Notice where in your body you feel the feeling most." },
      { text: "Describe it simply: tight, heavy, hot, fluttery." },
      { text: "Breathe out slowly, as if the breath could move around it." },
      { text: "See if you can let it be there, without needing it to change." },
      { text: "Remind yourself: this is a feeling. It is here, and it will change." },
      { text: "Open your eyes wide and look around the room before moving on." },
    ],
  },
  {
    id: "skill-self-kindness", type: "skill", title: "A moment of kindness",
    intro: "Three short steps for a moment when you're being hard on yourself.",
    whenToUse: "When your inner voice is harsh, or things feel like too much.",
    durationSec: 120, intensity: 1, tags: ["S09"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 6, imagery: false,
    sourceTechniqueId: "msc-self-compassion-break",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Name it: \"This is a hard moment.\"" },
      { text: "Remind yourself: \"Other people feel this too. I'm not the only one.\"" },
      { text: "Put a hand somewhere comforting, like your chest or your arm, if that feels okay." },
      { text: "Offer yourself one kind sentence, the way you might to a friend." },
      { text: "If kindness feels hard right now, that's common. Noticing is enough." },
    ],
  },
  {
    id: "skill-not-all-of-you", type: "skill", title: "Not all of you",
    intro: "A strong feeling can be a part of you without being all of you.",
    whenToUse: "When a feeling seems to take over everything.",
    durationSec: 120, intensity: 1, tags: ["S10"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 6, imagery: false,
    sourceTechniqueId: "parts-not-all-of-you",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Name the feeling: \"Part of me feels ___.\"" },
      { text: "Notice what else is here too, even small: your feet on the floor, the light in the room, one thing you care about." },
      { text: "Try saying: \"Part of me feels ___, and I'm also here, noticing it.\"" },
      { text: "Take one slower breath out." },
    ],
  },
  {
    id: "skill-ride-the-urge", type: "skill", title: "Ride the urge",
    intro: "Urges rise, peak, and pass, like a wave. You can watch one without acting on it.",
    whenToUse: "When you feel a strong pull to do something you'd rather not.",
    skipIf: ["You're in danger or the urge is to hurt yourself. Open SOS instead."],
    durationSec: 240, intensity: 1, tags: ["S11"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 6, imagery: false,
    sourceTechniqueId: "exp-urge-surfing",
    signoffRowIds: ["CV10_A02", "CV10_A03", "CV10_A05"],
    steps: [
      { text: "Notice the urge. Name what it's pulling you toward." },
      { text: "Rate how strong it is, just for yourself." },
      { text: "Notice where you feel it in your body." },
      { text: "Breathe slowly and watch it, like watching a wave from the shore." },
      { text: "Notice any change in its strength. Up, down, or the same are all okay." },
      { text: "When it eases, even a little, notice that you rode it." },
    ],
  },
  {
    id: "skill-what-i-need", type: "skill", title: "What do I need?",
    intro: "A simple question that can point you toward one helpful next thing.",
    whenToUse: "When you feel off but aren't sure why.",
    durationSec: 120, intensity: 1, tags: ["S12"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 7, imagery: false,
    sourceTechniqueId: "human-what-do-you-need",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Pause and ask: \"What do I need right now?\"" },
      { text: "Some common answers: rest, food, water, quiet, company, movement, reassurance." },
      { text: "Pick the one that feels closest. It doesn't have to be exact." },
      { text: "Think of one small way to give yourself some of it in the next hour." },
    ],
  },
  {
    id: "skill-who-is-there", type: "skill", title: "Who's actually there",
    intro: "A quick map of the people and places that support you, even in small ways.",
    whenToUse: "When you feel alone, or before a hard stretch.",
    durationSec: 180, intensity: 1, tags: ["S13"], hasHold: false,
    minTier: AccessTier.STABILIZATION, maxActivation: 6, imagery: false,
    sourceTechniqueId: "ipt-support-map",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Think of one person you could text or call about something small." },
      { text: "Think of one person or place where you feel a little more at ease." },
      { text: "Think of one person who has helped you before, even once." },
      { text: "Choose one to reach out to this week, only if you want to." },
      { text: "If no one comes to mind right now, that's okay. Your SOS plan and the crisis line are always here." },
    ],
  },
  {
    id: "skill-catch-thought", type: "skill", title: "Catch the thought",
    intro: "Noticing the thought that came with a feeling is the first step to working with it.",
    whenToUse: "After a moment when your mood shifted.",
    durationSec: 180, intensity: 1, tags: ["S14"], hasHold: false,
    minTier: AccessTier.CAUTIOUS, maxActivation: 6, imagery: false,
    sourceTechniqueId: "cbt-thought-noticing",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Think of a recent, everyday moment when your mood dropped or spiked." },
      { text: "What was the feeling?" },
      { text: "What went through your mind just then? Write or say the thought as it came." },
      { text: "Notice: this is a thought, not a fact. It may or may not be true." },
    ],
  },
  {
    id: "skill-just-a-thought", type: "skill", title: "Just a thought",
    intro: "Stepping back from a sticky thought can loosen its grip.",
    whenToUse: "When one thought keeps repeating.",
    durationSec: 120, intensity: 1, tags: ["S15"], hasHold: false,
    minTier: AccessTier.CAUTIOUS, maxActivation: 6, imagery: false,
    sourceTechniqueId: "act-defusion",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Say the thought to yourself as it is." },
      { text: "Now add: \"I'm having the thought that ___.\"" },
      { text: "Now: \"I notice I'm having the thought that ___.\"" },
      { text: "Notice any change in how close or loud it feels." },
    ],
  },
  {
    id: "skill-thinking-traps", type: "skill", title: "Spot the thinking trap",
    intro: "Minds under stress take shortcuts. Naming the shortcut can take some of the sting out.",
    whenToUse: "When a thought feels harsh or absolute.",
    durationSec: 180, intensity: 1, tags: ["S16"], hasHold: false,
    minTier: AccessTier.CAUTIOUS, maxActivation: 5, imagery: false,
    sourceTechniqueId: "cbt-thinking-traps",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Write down the thought." },
      { text: "See if it fits a common trap: all-or-nothing, fortune telling, mind reading, \"should\" rules, or blaming yourself for everything." },
      { text: "Name the trap if one fits. It's fine if none does." },
      { text: "Ask: what would I say to a friend who had this thought?" },
    ],
  },
  {
    id: "skill-values-check", type: "skill", title: "What matters to me",
    intro: "A short check on what you care about, to help choose what to do next.",
    whenToUse: "On a steadier day, when you want some direction.",
    durationSec: 180, intensity: 1, tags: ["S17"], hasHold: false,
    minTier: AccessTier.STEADY, maxActivation: 4, imagery: false,
    sourceTechniqueId: "act-values-compass",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Pick an area: people, work or learning, health, fun, community, or something else." },
      { text: "In a few words, what kind of person do you want to be in that area?" },
      { text: "Think of one small action this week that fits." },
      { text: "Keep it small enough that it feels doable." },
    ],
  },
  {
    id: "skill-three-good", type: "skill", title: "Three good things",
    intro: "Noticing small good moments, on purpose.",
    whenToUse: "At the end of a day.",
    durationSec: 180, intensity: 1, tags: ["S18"], hasHold: false,
    minTier: AccessTier.STEADY, maxActivation: 4, imagery: false,
    sourceTechniqueId: "pp-three-good-things",
    signoffRowIds: ["CV10_A02", "CV10_A03"],
    steps: [
      { text: "Think of three things from today that went okay, or better. Small counts." },
      { text: "For each, notice what you were doing or who was there." },
      { text: "Let yourself stay with one of them for a breath or two." },
      { text: "If today was hard and nothing comes, one neutral moment is fine too." },
    ],
  },
];

/** A14: two new sleep practices, scripts and timings as written. Titles are
 *  the worksheet's own names for them (row A14). */
export const H10_SLEEP: Practice[] = [
  {
    id: "after-a-bad-dream", type: "sleep", title: "After a bad dream",
    intro: "For waking up from a bad dream. Eyes open, lights on if you like.",
    durationSec: 130, intensity: 1, tags: ["night"], hasHold: false,
    note: "You don't need to think about the dream. This is only about right now.",
    minTier: AccessTier.GROUNDING_ONLY, maxActivation: 10, imagery: false,
    signoffRowIds: ["CV10_A14"],
    segments: [
      { text: "You're awake. That was a dream, and it's over. You can turn on a light if you'd like.", seconds: 10 },
      { text: "Keep your eyes open. Look around the room. Find three things you recognize.", seconds: 14 },
      { text: "Feel the mattress under you. Feel the blanket, or the air on your skin.", seconds: 12 },
      { text: "Say, quietly or in your head, where you are and what today's date is.", seconds: 12 },
      { text: "Let your breath out a little slower than it comes in. No need to force it.", seconds: 14 },
      { text: "If your heart is still racing, that's your body settling after a false alarm. It will slow.", seconds: 14 },
      { text: "You don't need to go back over the dream. You can set it aside for now.", seconds: 12 },
      { text: "Stay with the room, the blanket, the slower breath out, for as long as you need.", seconds: 30 },
      { text: "When you feel a little more settled, you can lie back, or get up for a while. Both are okay.", seconds: 12 },
    ],
  },
  {
    id: "back-to-rest", type: "sleep", title: "Back to rest",
    intro: "For lying awake in the night with a busy mind.",
    durationSec: 194, intensity: 1, tags: ["night"], hasHold: false,
    note: "If you've been awake a while and feel frustrated, it's fine to get up for a bit instead.",
    minTier: AccessTier.STABILIZATION, maxActivation: 7, imagery: false,
    signoffRowIds: ["CV10_A14"],
    segments: [
      { text: "It's the middle of the night, and you're awake. That happens. There's nothing you have to solve right now.", seconds: 14 },
      { text: "Let your body be heavy on the bed. Notice where it's touching the mattress.", seconds: 14 },
      { text: "If thoughts come, let them come. You can tell them: not now, tomorrow.", seconds: 14 },
      { text: "Breathe in normally. Let the breath out slow down a little, like a long sigh.", seconds: 16 },
      { text: "Let your jaw loosen. Let your shoulders drop, just a little.", seconds: 14 },
      { text: "Let your hands go soft. Let your feet be heavy.", seconds: 14 },
      { text: "You don't need to sleep. Resting here, quietly, still helps.", seconds: 16 },
      { text: "Each time your mind wanders, just come back to the heaviness of your body.", seconds: 20 },
      { text: "Stay with that heaviness for as long as you like.", seconds: 60 },
      { text: "Rest is here whenever it comes.", seconds: 12 },
    ],
  },
];

/** 1D: eight lessons, rows A06 to A13 (L1 to L8), text as written. */
export const H10_LESSONS: Lesson[] = [
  {
    id: "always-on-alert",
    title: "When your body stays on alert",
    summary: "Why your body might stay switched on, and small ways to signal it can ease off.",
    readMinutes: 3,
    tags: ["L1"],
    relatedModuleIds: [],
    signoffRowIds: ["CV10_A06"],
    body: "## The idea\nAfter overwhelming or frightening experiences, the body's alarm system can stay turned up. You might startle easily, scan rooms, sit facing the door, or find it hard to relax even when things are calm. This is your body trying to protect you. It learned that staying ready kept you safer.\n\n## Why it lingers\nThe alarm doesn't always get the message that the danger has passed. So it keeps checking, and that takes energy. Many people describe feeling tired and wired at the same time.\n\n## What helps\nThe alarm settles through repeated, small signals of safety, not by arguing with it. Orienting to the room, feeling what's holding you up, and slower breaths out all send those signals. So does predictable routine, and time with people you feel at ease with.\n\n## A small practice\nNext time you notice yourself scanning, try \"Find the room\" and let your eyes rest on things you recognize. You're not telling the alarm it's wrong. You're giving it more information.",
  },
  {
    id: "shame",
    title: "Shame and the harsh inner voice",
    summary: "What shame is, why it's so common after hard experiences, and how kindness helps.",
    readMinutes: 3,
    tags: ["L2"],
    relatedModuleIds: [],
    signoffRowIds: ["CV10_A07"],
    body: "## The idea\nGuilt says \"I did something bad.\" Shame says \"I am bad.\" After hard experiences, many people carry shame for things that were never their fault. It often shows up as a harsh inner voice that criticizes, compares, or tells you to hide.\n\n## Why it's so sticky\nShame tends to make people pull away from others, and being alone with it makes it louder. It also resists logic. You can know something wasn't your fault and still feel ashamed.\n\n## What helps\nShame softens with warmth, not with argument. Speaking to yourself the way you'd speak to a friend, noticing that other people feel this too, and small moments of connection all work against it. This can feel awkward or even uncomfortable at first. That's common, and it gets easier.\n\n## A small practice\nWhen you catch the harsh voice, try \"A moment of kindness.\" You don't have to believe the kind words yet. Offering them is the practice.",
  },
  {
    id: "anger",
    title: "Anger makes sense",
    summary: "Anger as a protective signal, and ways to feel it without it running the show.",
    readMinutes: 3,
    tags: ["L3"],
    relatedModuleIds: [],
    signoffRowIds: ["CV10_A08"],
    body: "## The idea\nAnger is a normal, protective emotion. It shows up when something feels unfair, threatening, or crosses a line. After hard experiences, anger can arrive faster and hotter than before, sometimes over small things.\n\n## What's underneath\nAnger is often standing guard over something softer: hurt, fear, exhaustion, or feeling powerless. Noticing what's underneath doesn't mean the anger is wrong. It gives you more choices.\n\n## What helps\nThe goal isn't to get rid of anger. It's to have a gap between feeling it and acting on it. A pause, a slower breath out, or moving your body can widen that gap. Once the heat drops a little, you can decide what you want to do.\n\n## A small practice\nTry \"Pause before reacting\" the next time you feel the heat rise. If you need to burn off energy first, \"Move it out\" can help.\n\nIf anger ever leads you toward hurting yourself or someone else, open SOS or contact the crisis line.",
  },
  {
    id: "feeling-far-away",
    title: "Feeling far away",
    summary: "Why the mind sometimes steps back from the present, and how to come back gently.",
    readMinutes: 3,
    tags: ["L4"],
    relatedModuleIds: [],
    signoffRowIds: ["CV10_A09"],
    body: "## The idea\nSometimes, when things feel like too much, the mind turns the volume down. You might feel numb, foggy, far away, like you're watching yourself, or like the world isn't quite real. This is a protective response. It helped at some point by creating distance from something overwhelming.\n\n## Why it matters\nFeeling far away can be scary, and it can make it hard to take things in or remember them. It isn't dangerous in itself, and it usually passes.\n\n## What helps\nComing back is about the senses and the present moment: eyes open, noticing the room, feeling your feet and what's holding you up, gentle temperature, naming the date. Go slowly. The aim is to come back a little, not all at once.\n\n## A small practice\n\"Find the room\" and \"What's holding you up\" are made for this. If you notice this happening often, or for long stretches, it's worth mentioning to a doctor or counselor.",
  },
  {
    id: "stress-and-sleep",
    title: "Stress and sleep",
    summary: "How stress and rest affect each other, and why small habits matter.",
    readMinutes: 3,
    tags: ["L5"],
    relatedModuleIds: [],
    relatedProgramIds: ["steadier-sleep"],
    signoffRowIds: ["CV10_A10"],
    body: "## The idea\nStress and sleep feed each other. A body on alert finds it harder to fall and stay asleep, and poor sleep makes it harder to cope with stress the next day. Bad dreams and waking in the night are common after stressful times.\n\n## Why habits help\nSleep isn't something you can force. Trying hard to sleep usually keeps you more awake. What you can do is set things up so sleep is more likely: a steady getting-up time, a wind-down routine, and a bed your body links with rest rather than lying awake.\n\n## What to expect\nChanges to sleep habits often feel harder before they feel easier, and improvements tend to be gradual. A bad night doesn't undo your progress.\n\n## A small practice\nPick one wind-down habit for tonight. Just one.\n\nIf you snore loudly, stop breathing in your sleep, or feel sleepy while driving, please talk to a doctor. Those are worth checking.",
  },
  {
    id: "trust-and-closeness",
    title: "Trust and closeness",
    summary: "Why relationships can feel complicated after hard experiences, and small ways forward.",
    readMinutes: 3,
    tags: ["L6"],
    relatedModuleIds: [],
    relatedProgramIds: ["feeling-and-relating"],
    signoffRowIds: ["CV10_A11"],
    body: "## The idea\nHard experiences, especially ones involving other people, can change how safe closeness feels. You might want connection and also feel wary of it. You might expect to be let down, find it hard to ask for things, or keep people at a distance.\n\n## Why it makes sense\nThese patterns are usually lessons your mind learned to protect you. They made sense then. The question now is whether they still fit the people in your life today.\n\n## What helps\nSmall, low-stakes moments of connection, with people who have shown they're reasonably safe, help build trust gradually. So does practicing saying what you need in small ways. There's no need to go faster than feels okay.\n\n## A small practice\nTry \"Who's actually there\" to notice the support around you, even if it's small.",
  },
  {
    id: "coping-that-costs",
    title: "Coping that costs more later",
    summary: "Why some ways of coping help now but cost later, without judgment.",
    readMinutes: 3,
    tags: ["L7"],
    relatedModuleIds: [],
    signoffRowIds: ["CV10_A12"],
    body: "## The idea\nEveryone reaches for ways to feel better fast. Some of those ways, like drinking, scrolling for hours, overworking, avoiding people, or using substances, bring quick relief but make things harder over time.\n\n## Why it happens\nThese habits work, briefly. That's why they stick. Needing relief isn't a flaw. It's a sign that something hurts.\n\n## What helps\nRather than trying to stop everything at once, it helps to add options. Having a few quick, healthier ways to ease strong feelings makes it easier to choose them sometimes. Noticing the urge and riding it out, even once, builds that skill.\n\n## A small practice\nTry \"Ride the urge\" the next time you feel a pull toward a habit that costs you. If you're worried about your use of alcohol or drugs, a doctor or counselor can help, and it's okay to ask.",
  },
  {
    id: "action-before-motivation",
    title: "Action before motivation",
    summary: "Why small actions can come before feeling like doing them.",
    readMinutes: 3,
    tags: ["L8"],
    relatedModuleIds: [],
    relatedProgramIds: ["moving-toward"],
    signoffRowIds: ["CV10_A13"],
    body: "## The idea\nWhen mood is low, it's natural to wait until you feel like doing things. But low mood tends to shrink what we do, and doing less tends to lower mood further. It becomes a loop.\n\n## Flipping the order\nOne of the most practical ways out of that loop is to act first, in small ways, and let the feeling follow. Not big changes. Small, doable steps connected to things you care about.\n\n## What counts\nAnything that gives a small sense of getting something done, of enjoyment, or of connection. Opening a window counts. Replying to one message counts. So does ten minutes on something you used to enjoy.\n\n## What to expect\nAt first, activities may not feel as good as they used to. That's normal. The good feelings often come back gradually as you keep going.\n\n## A small practice\nThink of one thing you could do in the next day that would take less than ten minutes.",
  },
];
