import { ReviewPage } from "@/components/clinical/ReviewPage";
import { Panel, Callout, SummaryCards } from "@/components/app/surfaces";
import { requireReviewAccess } from "@/lib/auth";
import type { WorkState } from "@/lib/governance/work-register";
import {
  OPEN_DECISIONS, decisionSummary, AUDIENCE_LABEL,
} from "@/lib/governance/decision-register";
import {
  registerRows, registerAreas, registerSummary, unfinished,
  STATE_LABEL, STATE_ADVICE, type RegisterRow,
} from "@/lib/review/work-register-view";

export const dynamic = "force-dynamic";
export const metadata = { title: "Work register — Steady Review" };

// The work register, on a screen.
//
// THE REGISTER EXISTS BECAUSE HANDOFF PARAGRAPHS GO STALE, and until now its
// only reader was the test suite. Somebody asking "is assigned support built?"
// had two options: open `src/lib/governance/work-register.ts`, or ask a
// document — and asking a document is the failure the register was written to
// stop. Four instances turned up in one week, including a feature that was
// fully built, fully tested, and reachable from nothing.
//
// WHY THE EVIDENCE IS ON THE ROW rather than behind a state badge. A word like
// "reachable" is exactly the kind of claim that goes stale, and a screen that
// printed the word and nothing else would be a prettier version of the
// paragraph it replaces. Each entry carries the three things the source was
// asked: the symbol is there, a test names it, and something outside its own
// module uses it. The reader can disbelieve the word and read the receipts.
//
// WHAT THIS SCREEN CANNOT DO is tell you the feature is any good. The third
// check proves a person can reach it, not that reaching it helps them. The
// testing console is where that question is asked.

const STATE_TONE: Record<WorkState, string> = {
  reachable: "border-state-good/40 bg-state-good-bg/50",
  tested: "border-state-info/40 bg-state-info-bg/60",
  built: "border-state-caution/40 bg-state-caution-bg",
  held: "border-state-caution/40 bg-state-caution-bg",
  proposed: "border-ground/15 bg-linen/40",
  superseded: "border-ground/15 bg-linen/40",
};

function Entry({ row }: { row: RegisterRow }) {
  const { entry, finding, evidence, drifted } = row;
  return (
    <li className={`rounded-xl border p-4 ${STATE_TONE[entry.state]}`}>
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <p className="text-sm font-semibold">{entry.title}</p>
        <span className="text-xs text-olive">{STATE_LABEL[entry.state]}</span>
      </div>
      <p className="mt-0.5 font-mono text-xs text-olive">{entry.id}</p>

      {entry.note && <p className="mt-2 text-xs">{entry.note}</p>}

      <ul className="mt-2 space-y-1">
        {evidence.map((e) => (
          <li key={e.claim} className="grid gap-0.5 text-xs sm:grid-cols-[14rem_minmax(0,1fr)] sm:gap-3">
            {/* The claim and its answer are two cells, so a long file path
                wraps in its own column instead of pushing the claim off the
                row at 320px. `minmax(0,1fr)` because a bare `1fr` keeps its
                automatic minimum and a long symbol name then scrolls the
                page sideways. */}
            <span className="min-w-0 text-olive">
              {/* NOT COLOUR ALONE. A tone class on the row and a tick would
                  leave a reader who cannot see the tone with a list of
                  sentences and no verdict. */}
              {e.met ? "Yes" : "No"} — {e.claim}
            </span>
            <span className="min-w-0 break-words font-mono">{e.detail}</span>
          </li>
        ))}
      </ul>

      {drifted && (
        <div className="mt-2 rounded-lg border border-state-support/40 bg-state-support-bg/60 p-2">
          <p className="text-xs font-medium">The source does not support this entry&rsquo;s own claim.</p>
          <ul className="mt-1 list-disc space-y-0.5 pl-4 text-xs">
            {finding.problems.map((p) => <li key={p}>{p}</li>)}
          </ul>
        </div>
      )}
    </li>
  );
}

export default async function WorkRegisterPage() {
  await requireReviewAccess();

  // The COMMITTED walk, not a fresh one — `verifyRegister` reads `src` and
  // `tests` off disk, and neither is present in a deployed standalone build.
  // Generated by scripts/gen-work-register.ts and held to a fresh walk by
  // tests/work-register.test.ts, the same arrangement as the access inventory.
  const rows = registerRows();
  const areas = registerAreas(rows);
  const summary = registerSummary(rows);
  const open = unfinished(rows);
  const decisions = decisionSummary();
  const openDecisions = OPEN_DECISIONS;

  return (
    <ReviewPage
      title="Work register"
      lede="What is built, what it rests on, and what the source says when it is asked."
      layer="audit"
      here="/review/work"
    >
      {/* THREE, BECAUSE THE SHELL ALLOWS THREE. A fourth card throws at render
          time, which the build and 2,760 node tests all passed straight over
          and a single page load found. The one dropped is "not finished" — it
          has a panel of its own below, where each entry arrives with its
          reason, and a bare count of unbuilt work is the least useful way to
          say it. */}
      <SummaryCards
        cards={[
          {
            label: "Entries",
            value: String(summary.entries),
            detail: "each naming its code and the test that exercises it",
          },
          {
            label: "Built and reachable",
            value: `${summary.byState.reachable} of ${summary.entries}`,
            detail: "a person can get to it from a screen",
          },
          {
            label: "Waiting on a person",
            value: String(decisions.open),
            detail: "questions nobody has answered, each with what happens meanwhile",
          },
        ]}
      />

      <Callout tone={summary.drifted === 0 ? "info" : "caution"} label="What this screen is for">
        {summary.drifted === 0
          ? `Every entry below was checked against the source on the last build, and the source agreed with all ${summary.entries} of them. ` +
            "That is the claim worth making: not that the list is long, but that nothing on it is a sentence somebody " +
            "wrote and nobody re-read. A feature built, tested and reachable from nothing would appear here as a problem " +
            "rather than as a green row — that is the check this register was written for."
          : "At least one entry claims more than the source supports. The suite is already failing on it; the rows are " +
            "marked below."}
      </Callout>

      {/* WAITING ON A PERSON, ABOVE THE WORK. Neither register could say this:
          `proposed`, `held` and `gap` all describe the state of the WORK, and
          none of them says "this is not moving because nobody has answered a
          question". A reader who cannot tell those apart cannot tell whether
          building harder would help. */}
      {openDecisions.length > 0 && (
        <Panel
          title="Waiting on a person"
          footnote={`${decisions.open} open, ${decisions.answered} answered. Each says what happens while nobody has answered, because an unanswered question always has a current behaviour and leaving it unsaid is how a default becomes a decision nobody took.`}
        >
          <ul className="space-y-3">
            {openDecisions.map((d) => (
              <li key={d.id} className="rounded-xl border border-state-info/40 bg-state-info-bg/50 p-4">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <p className="text-sm font-semibold">{AUDIENCE_LABEL[d.audience]}</p>
                  <span className="text-xs text-olive">asked {d.asked}</span>
                </div>
                <p className="measure mt-1 text-sm">{d.question}</p>
                <p className="measure mt-2 text-xs text-olive">
                  <span className="font-medium">Meanwhile:</span> {d.meanwhile}
                </p>
                {d.blocks.length > 0 && (
                  <p className="mt-1 font-mono text-xs text-olive">
                    Holds up: {d.blocks.join(", ")}
                  </p>
                )}
              </li>
            ))}
          </ul>
        </Panel>
      )}

      {open.length > 0 && (
        <Panel
          title="Not built, and why"
          footnote={`${open.length} of ${summary.entries}. Lifted out of the list rather than left to be found in it: this is the half of the register a stale document gets wrong in the expensive direction — somebody rebuilds what exists, or promises what does not.`}
        >
          <ul className="space-y-3">
            {open.map((row) => (
              <li key={row.entry.id} className="rounded-xl border border-ground/15 bg-app-surface p-4">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <p className="text-sm font-semibold">{row.entry.title}</p>
                  <span className="text-xs text-olive">{STATE_LABEL[row.entry.state]}</span>
                </div>
                <p className="mt-0.5 font-mono text-xs text-olive">{row.entry.id}</p>
                <p className="mt-2 text-xs">{STATE_ADVICE[row.entry.state]}</p>
                {row.entry.note && <p className="mt-1 text-xs text-olive">{row.entry.note}</p>}
              </li>
            ))}
          </ul>
        </Panel>
      )}

      {areas.map((area) => (
        <Panel
          key={area.area}
          title={area.label}
          footnote={`${area.rows.length} entr${area.rows.length === 1 ? "y" : "ies"}`}
        >
          <ul className="space-y-3">
            {area.rows.map((row) => <Entry key={row.entry.id} row={row} />)}
          </ul>
        </Panel>
      ))}

      <Panel title="What the states mean">
        <dl className="space-y-1 text-xs">
          {(Object.keys(STATE_LABEL) as WorkState[]).map((s) => (
            <div key={s} className="grid gap-1 sm:grid-cols-[16rem_minmax(0,1fr)] sm:gap-3">
              <dt className="min-w-0 text-olive">{STATE_LABEL[s]}</dt>
              <dd className="min-w-0">{STATE_ADVICE[s]}</dd>
            </div>
          ))}
        </dl>
      </Panel>
    </ReviewPage>
  );
}
