import { ReviewPage } from "@/components/clinical/ReviewPage";
import { Panel, Callout, SummaryCards } from "@/components/app/surfaces";
import { requireReviewAccess } from "@/lib/auth";
import {
  ACCESS_STEPS, ACCESS_EXEMPTIONS, STATIC_PROOF_LIMIT, exemption,
} from "@/lib/governance/access-sequence";
import { ACCESS_INVENTORY } from "@/lib/governance/access-inventory.generated";

export const dynamic = "force-dynamic";
export const metadata = { title: "Access enforcement — Steady Review" };

// The security evidence screen (handoff 06 §30.6, §31.5).
//
// §31.5's acceptance requirement for Security is unlike the other eight. Every
// other audience is asked whether they can DO something; Security is asked
// whether it can PROVE something — "prove tenant, role, consent, purpose and
// minimum-necessary enforcement for every protected endpoint". A claim about
// every endpoint cannot be made by reading a few of them.
//
// So this screen is an INVENTORY, not a dashboard. Every protected route in the
// register is checked against the steps it owes, and the answer is one of four
// things, each of which reads differently on purpose:
//
//   SHOWN         The evidence is in the code that runs on this route.
//   NOT SHOWN     It is owed and the evidence is not visible at the depth this
//                 looks. That is a reviewer's question, not a verdict.
//   EXEMPT        The route declares it does not owe the step, with a reason
//                 that is printed here rather than left in a comment.
//   BEHAVIOURAL   The step has no single named mechanism to find, and the
//                 tests that attack it are named instead.
//
// WHAT THIS SCREEN REFUSES TO DO is imply that a full row of green is a proof
// of security. Finding a guard proves the guard is called. The boundary tests
// named against each step are what prove it is right, and they work by
// attacking the boundary rather than by reading it.

const AUDIENCE_ORDER = ["member", "clinician", "reviewer", "organization", "payer", "demo_admin"];

export default async function AccessEnforcementPage() {
  await requireReviewAccess();

  // The COMMITTED walk, not a fresh one. The inventory is derived from source,
  // and source is not present at runtime in a deployed build — a page that
  // walked the tree would be reading files that are not there, and Turbopack
  // said so in stronger terms: a dynamic filesystem read from a server
  // component traces the whole project into the server bundle. So the walk is
  // generated by scripts/gen-access-inventory.ts, checked in, and held to a
  // fresh walk by tests/access-enforcement.test.ts.
  const inv = ACCESS_INVENTORY;
  const behavioural = ACCESS_STEPS.filter((s) => s.proof === "behaviourally");
  const withGaps = inv.routes.filter((r) => r.missing.length > 0);

  return (
    <ReviewPage
      title="Access enforcement"
      lede="Every protected route, against every step of the permission sequence it owes."
    >
      <SummaryCards
        cards={[
          {
            label: "Protected routes",
            value: String(inv.protectedCount),
            detail: "checked against the steps each one owes",
          },
          {
            label: "No gap",
            value: `${inv.complete} of ${inv.protectedCount}`,
            detail: "every owed step shown, or declared exempt with a reason",
          },
          {
            label: "Routes with a question",
            value: String(withGaps.length),
            detail: "at least one owed step not shown here",
          },
        ]}
      />

      <Callout tone="caution" label="What a full row does not prove">
        {STATIC_PROOF_LIMIT}
      </Callout>

      <Panel
        title="The sequence"
        footnote="The steps, their checks and their failure behaviours are the handoff's, unchanged. What each step accepts as evidence, and which tests attack it, are this product's."
      >
        <div className="space-y-3">
          {ACCESS_STEPS.map((s) => {
            const gaps = inv.gapsByStep[s.n] ?? 0;
            return (
              <div key={s.n} className="rounded-xl border border-ground/10 bg-app-surface p-4">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <p className="text-sm font-semibold">
                    <span className="tabular-nums text-ground/50">{s.n}.</span> {s.name}
                  </p>
                  <span className="text-xs text-ground/60">
                    {s.proof === "behaviourally"
                      ? "no single mechanism to find — proven by attack"
                      : gaps === 0
                        ? "shown everywhere it is owed"
                        : gaps === 1
                          ? "1 route owes this and does not show it"
                          : `${gaps} routes owe this and do not show it`}
                  </span>
                </div>
                <dl className="mt-2 space-y-1 text-xs">
                  <div className="grid gap-1 sm:grid-cols-[9rem_1fr] sm:gap-3">
                    <dt className="text-ground/60">Check</dt>
                    <dd>{s.check}</dd>
                  </div>
                  <div className="grid gap-1 sm:grid-cols-[9rem_1fr] sm:gap-3">
                    <dt className="text-ground/60">On failure</dt>
                    <dd>{s.onFailure}</dd>
                  </div>
                  {s.evidence.length > 0 && (
                    <div className="grid gap-1 sm:grid-cols-[9rem_1fr] sm:gap-3">
                      <dt className="text-ground/60">Evidence</dt>
                      <dd className="break-words">
                        {s.evidence.map((e) => <code key={e} className="mr-2">{e}</code>)}
                      </dd>
                    </div>
                  )}
                  <div className="grid gap-1 sm:grid-cols-[9rem_minmax(0,1fr)] sm:gap-3">
                    <dt className="text-ground/60">Attacked by</dt>
                    <dd className="min-w-0 break-words">
                      {s.attackedBy.map((t) => <code key={t} className="mr-2">{t}</code>)}
                    </dd>
                  </div>
                </dl>
              </div>
            );
          })}
        </div>
      </Panel>

      {behavioural.length > 0 && (
        <Callout tone="info" label="One step has no marker, on purpose">
          {behavioural.map((s) => s.name).join(", ")} has no single named mechanism in this
          codebase. Minimum-necessary here is a property of what the projections can return at
          all — the aggregate population has no names in the database, so an aggregate console
          cannot leak one whatever it asks. That is a stronger guarantee than a filter and it is
          invisible to a scan of the route, so it is reported as proven by attack rather than
          given a marker that would turn its absence into a green cell.
        </Callout>
      )}

      <Panel
        title="Open questions"
        footnote="A route here owes a step and does not show it at the depth this looks. That is either a real gap or a mechanism further down than one call — both worth a reviewer's attention, neither a verdict."
      >
        {withGaps.length === 0 ? (
          <p className="text-sm text-ground/70">
            Every protected route shows every step it owes. That is not the same as being
            secure — see the note above.
          </p>
        ) : (
          <div className="space-y-3">
            {ACCESS_STEPS.filter((s) => (inv.gapsByStep[s.n] ?? 0) > 0).map((s) => {
              const routes = inv.routes.filter((r) => r.missing.includes(s.n));
              return (
                <div key={s.n} className="rounded-xl border border-ground/10 bg-app-surface p-4">
                  <p className="text-sm font-semibold">
                    Step {s.n} — {s.name}
                  </p>
                  <p className="mt-1 text-xs text-ground/70">
                    {routes.length === 1
                      ? "1 route owes this and does not show it."
                      : `${routes.length} routes owe this and do not show it.`}
                  </p>
                  <p className="mt-2 break-words text-xs text-ground/70">
                    {routes.map((r) => <code key={r.path} className="mr-2">{r.path}</code>)}
                  </p>
                </div>
              );
            })}
          </div>
        )}
      </Panel>

      <Panel
        title="Declared exemptions"
        footnote="A step a named route does not owe, and why. Printed rather than subtracted: a reviewer who disagrees with one should find it in a list rather than by noticing an absence."
      >
        <div className="space-y-2">
          {ACCESS_EXEMPTIONS.map((e) => (
            <div key={`${e.path}-${e.step}`} className="rounded-xl border border-ground/10 bg-app-surface p-4">
              <p className="text-sm">
                <code>{e.path}</code>{" "}
                <span className="text-ground/60">does not owe step {e.step}</span>
              </p>
              <p className="measure mt-1 text-xs text-ground/80">{e.reason}</p>
            </div>
          ))}
        </div>
      </Panel>

      <Panel
        title="Every protected route"
        footnote="Grouped by audience, in register order. A dash means the route does not owe that step."
      >
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <caption className="sr-only">
              Each protected route against the eight steps of the permission and consent sequence
            </caption>
            <thead className="uppercase text-ground/60">
              <tr>
                <th scope="col" className="px-2 py-2">Route</th>
                {ACCESS_STEPS.map((s) => (
                  <th key={s.n} scope="col" className="px-2 py-2 text-center" title={s.name}>
                    {s.n}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {AUDIENCE_ORDER.flatMap((audience) => {
                const rows = inv.routes.filter((r) => r.audience === audience);
                if (rows.length === 0) return [];
                return [
                  <tr key={`h-${audience}`} className="bg-moss/40">
                    <th scope="rowgroup" colSpan={ACCESS_STEPS.length + 1} className="px-2 py-1.5 text-left font-medium">
                      {audience} — {rows.length} route{rows.length === 1 ? "" : "s"}
                    </th>
                  </tr>,
                  ...rows.map((r) => (
                    <tr key={r.path} className="border-t border-ground/5">
                      <th scope="row" className="px-2 py-1.5 text-left font-normal">
                        <code>{r.path}</code>
                      </th>
                      {ACCESS_STEPS.map((s) => {
                        const owed = r.owed.includes(s.n);
                        const isExempt = r.exempt.includes(s.n);
                        const shown = owed && (r.found[s.n]?.length ?? 0) > 0;
                        const label = !owed
                          ? "—"
                          : isExempt
                            ? "exempt"
                            : s.proof === "behaviourally"
                              ? "attack"
                              : shown ? "shown" : "not shown";
                        const title = shown ? (r.found[s.n] ?? []).join(", ")
                          : isExempt ? (exemption(r.path, s.n)?.reason ?? "") : undefined;
                        return (
                          <td key={s.n} className="px-2 py-1.5 text-center" title={title}>
                            <span className={label === "not shown" ? "font-medium text-state-serious" : "text-ground/70"}>
                              {label}
                            </span>
                          </td>
                        );
                      })}
                    </tr>
                  )),
                ];
              })}
            </tbody>
          </table>
        </div>
      </Panel>
    </ReviewPage>
  );
}
