#!/usr/bin/env tsx
// The approval document, generated from the vocabulary it approves.
//
// WHY GENERATED. The document is what a reviewer reads and signs; the module is
// what the product renders. If they are maintained separately they drift, and
// the drift is invisible — a signature over a list of words that no longer
// matches the words on screen is the failure this whole mechanism exists to
// prevent, reproduced one level up.
//
// So the document is derived, a guard asserts it is current, and the hash in
// the approval record ties the signature to the content rather than to the file.
//
//   npx tsx scripts/gen-approval-document.ts

import fs from "node:fs";
import path from "node:path";
import { EVENT_TERMS } from "../src/lib/clinical/event-vocabulary";
import {
  DISPLAY_VOCABULARY_APPROVAL as A, vocabularyHash,
} from "../src/lib/governance/clinical-approval";

function render(): string {
  const hash = vocabularyHash();
  const keys = Object.keys(EVENT_TERMS).sort();
  const lines: string[] = [];

  lines.push(`# Clinical approval — ${A.id}`);
  lines.push("");
  lines.push("<!-- Generated by scripts/gen-approval-document.ts. Do not edit by hand:");
  lines.push("     the words live in src/lib/clinical/event-vocabulary.ts and this file is");
  lines.push("     derived from them, so the two cannot disagree. -->");
  lines.push("");
  lines.push("## Status");
  lines.push("");
  if (A.status === "approved") {
    lines.push(`**Approved** on ${A.reviewedAt} by:`);
    lines.push("");
    for (const r of A.reviewers) lines.push(`- ${r.name} — ${r.role}`);
  } else {
    lines.push("**Awaiting attestation.** No reviewer and no date have been recorded against");
    lines.push("this content. Until they are, the product renders these words as carrying no");
    lines.push("clinical approval, and `checkApproval()` fails with that reason.");
    lines.push("");
    lines.push("To record the attestation, set `status`, `reviewers` and `reviewedAt` in");
    lines.push("`src/lib/governance/clinical-approval.ts`, then regenerate this document.");
  }
  lines.push("");
  lines.push("## What the approval is tied to");
  lines.push("");
  lines.push(`Content hash \`${A.contentHash}\``);
  lines.push("");
  lines.push(
    A.contentHash === hash
      ? "The vocabulary currently hashes to the same value, so the words below are the words the attestation covers."
      : `**The vocabulary has changed since the attestation.** It now hashes to \`${hash}\`. The approval does not cover the current words.`
  );
  lines.push("");
  lines.push("The hash is taken over every key, its term AND its note, sorted by key. The");
  lines.push("note is included because that is where the clinical boundary lives — \"recorded");
  lines.push("is not delivered\", \"opened is not reviewed\". Changing a single word in any");
  lines.push("note changes the hash and invalidates the approval.");
  lines.push("");
  lines.push("## Scope");
  lines.push("");
  lines.push(A.scope);
  lines.push("");
  lines.push("Appears on:");
  lines.push("");
  for (const s of A.appliesTo) lines.push(`- \`${s}\``);
  lines.push("");
  lines.push("## What this approval does NOT cover");
  lines.push("");
  for (const e of A.excludes) lines.push(`- ${e}`);
  lines.push("");
  lines.push(`## The approved words (${keys.length})`);
  lines.push("");
  lines.push("The raw key is retained everywhere the term is shown — the term is what the");
  lines.push("column displays, the key stays one disclosure away.");
  lines.push("");
  lines.push("| Event key | Clinician-facing term | What it means, and what it does not |");
  lines.push("|---|---|---|");
  for (const k of keys) {
    const t = EVENT_TERMS[k];
    lines.push(`| \`${k}\` | ${t.term} | ${t.note.replace(/\|/g, "\\|")} |`);
  }
  lines.push("");
  lines.push("## Anything not listed here");
  lines.push("");
  lines.push("An event key absent from this table renders as its raw value and is marked on");
  lines.push("screen as carrying no approved words. It is not guessed at, and it is not");
  lines.push("covered by this approval.");
  lines.push("");
  return lines.join("\n");
}

const out = path.join(process.cwd(), A.document);
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, render());
console.log(`wrote ${A.document}: ${Object.keys(EVENT_TERMS).length} approved terms, status ${A.status}`);
