// The companion's entry disclosure (handoff 09 §11).
//
// §11 lists AI companion placement as an open decision, and its objection is
// structural rather than cosmetic: "The companion does not appear in the Vol 2
// session state machine at all. It needs a defined position relative to the
// routing engine before it gets a position on screen." Until that position
// exists, it attaches one interim condition:
//
//   "Until then, ENTRY STATES IT IS AI and NAMES ITS COMMUNICATION LIMITS."
//
// DECIDED 2026-09-09: keep the companion where it is, and meet that condition
// properly. It was not met. The companion carried one line — "Your companion is
// supportive software, not a therapist or emergency care" — and it sat BELOW
// the message thread, after the conversation, where it is read (if at all) by
// somebody who has already used the thing. §11 says ENTRY.
//
// AND "SUPPORTIVE SOFTWARE" IS NOT "AI". A spreadsheet is supportive software.
// The condition is specific because the thing a person needs to know before
// typing something private is not that a program is involved — it is that the
// replies are generated, and that no person is reading them.
//
// THE LIMITS ARE NAMED, not gestured at. §11 says "names its communication
// limits", which is a different requirement from a disclaimer: a disclaimer
// protects the product, and this is supposed to tell somebody what will and
// will not happen when they type. So each entry below is a thing the companion
// cannot do, said plainly, and the set is deliberately short enough to be read.
//
// NO IMPORTS. Rendered by a client component; a disclosure that drags a
// database driver into the browser bundle is its own defect.

/** §8.5: every member-facing string is a versioned copy key. */
export const COMPANION_ENTRY_COPY = {
  heading: "companion.entry.heading.v1",
  isAi: "companion.entry.is_ai.v1",
  limits: "companion.entry.limits.v1",
} as const;

export const COMPANION_ENTRY_MESSAGE: Record<string, string> = {
  "companion.entry.heading.v1": "Before you start",
  "companion.entry.is_ai.v1":
    "Your companion is AI. The replies are generated by software, not written by a person, and nobody reads this conversation as you type it.",
  "companion.entry.limits.v1": "What it cannot do:",
};

/**
 * The named limits (§11: "names its communication limits").
 *
 * Each is a thing that will not happen, written as the person would find out
 * the hard way. None is a legal formula, and none of them is "this is not
 * medical advice" — which is true, and tells nobody anything about what typing
 * here will do.
 */
export const COMPANION_LIMITS: ReadonlyArray<{ id: string; text: string }> = [
  {
    id: "not_monitored",
    text: "Nobody is watching this conversation. It does not reach your care team, and writing something here does not raise an alert.",
  },
  {
    id: "no_memory_promise",
    text: "It is not a record of your care. What you say here is not part of your clinical notes and is not what a clinician reads.",
  },
  {
    id: "not_emergency",
    text: "It cannot help in an emergency. In danger right now, call or text 988, or call 911.",
  },
  {
    id: "not_the_session",
    text: "It does not run your sessions or decide what is available to you. That is the program, and this sits beside it.",
  },
];

/**
 * Whether the disclosure has been placed where §11 requires.
 *
 * A predicate rather than a comment, because "at entry" is the part that
 * silently stops being true: a later edit that moves this below the thread, or
 * renders it only after the first message, leaves every word intact and undoes
 * the condition entirely. `beforeFirstExchange` is what the guard checks.
 */
export function meetsEntryCondition(placement: {
  beforeFirstExchange: boolean;
  statesItIsAi: boolean;
  namesLimits: number;
}): boolean {
  return (
    placement.beforeFirstExchange &&
    placement.statesItIsAi &&
    placement.namesLimits >= COMPANION_LIMITS.length
  );
}

/**
 * The one thing §11 actually asserts about position, held as a rule.
 *
 * The companion has no place in the Vol 2 session state machine. That is not a
 * gap to fill by choosing a place — choosing one is the founder decision §11
 * reserves — but it does license a negative: whatever position it eventually
 * gets, it is not a step inside a session, because the state machine that
 * defines those steps does not contain it.
 */
export const COMPANION_IS_NOT_A_SESSION_STEP = true;
