import { NextResponse } from "next/server";
import { requireIntelligence } from "@/lib/auth";
import { data } from "@/lib/data";
import { verifySignature } from "@/lib/intelligence/export";
import { resolveOrgTenant, resolvePayerTenant } from "@/lib/intelligence/scope";
import { audit } from "@/lib/audit";

// Fetching a governed export.
//
// The file is REBUILT from the recorded job rather than stored, and served
// only when its signature verifies. That ordering matters: a stored blob whose
// signature is checked at write time can be altered afterwards and still be
// served; a signature checked at read time cannot.
//
// Every fetch is audited, not only the creation. A file downloaded five times
// by three people is a different disclosure from one downloaded once, and the
// creation record alone cannot tell them apart.

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const user = await requireIntelligence();

  const c = await data();
  const row = (await c.get(
    `SELECT id, tenant_id, purpose, surface, cohort_version, filter_hash,
            content_hash, signature, created_at
       FROM export_jobs WHERE id = ?`,
    [id],
  )) as Record<string, unknown> | undefined;

  // Not found rather than forbidden, for an export belonging to another
  // tenant: "forbidden" confirms the export exists.
  if (!row) return new NextResponse("Not found", { status: 404 });

  // The tenant check, at READ time. Creating an export is scoped, but an id is
  // a URL — it gets pasted into a ticket, kept in a bookmark, and fetched
  // again by whoever has it. Without this, holding an id was enough to read
  // any tenant's purpose, cohort and filter: a disclosure the creating scope
  // check never authorised.
  //
  // Scope here is the same resolution the consoles use, because role
  // assignments do not yet carry the binding (see scope.ts). It is narrower
  // than it looks — the facility tenants and the platform tenant are excluded
  // — and it is the one line to change when the binding lands.
  const inScope = (await Promise.all([resolveOrgTenant(), resolvePayerTenant()]))
    .filter((t): t is string => t !== null);
  if (!inScope.includes(String(row.tenant_id))) {
    // Audited, then denied. A fetch for an export outside the caller's scope
    // is exactly the event a disclosure log exists to hold, and answering 404
    // to the caller does not mean answering nothing to the record.
    await audit({
      actorId: user.id,
      actorRole: user.role,
      family: "security",
      type: "export_out_of_scope",
      target: String(row.surface),
      detail: { exportId: id },
    });
    return new NextResponse("Not found", { status: 404 });
  }

  if (!verifySignature(String(row.content_hash), String(row.signature))) {
    // A record whose signature does not verify is not served at all. It has
    // either been tampered with or was written under a different key, and
    // neither is a file to hand someone.
    await audit({
      actorId: user.id,
      actorRole: user.role,
      family: "security",
      type: "export_signature_invalid",
      target: String(row.surface),
      detail: { exportId: id },
    });
    return new NextResponse("This export cannot be verified and will not be served.", {
      status: 409,
    });
  }

  const rebuilt = (await c.get(
    "SELECT filter_json, row_count, suppressed_cells FROM export_jobs WHERE id = ?",
    [id],
  )) as { filter_json: string; row_count: number; suppressed_cells: number } | undefined;

  await audit({
    actorId: user.id,
    actorRole: user.role,
    family: "security",
    type: "export_downloaded",
    target: String(row.surface),
    detail: { exportId: id, contentHash: String(row.content_hash) },
  });

  // The manifest, not the data. The rows themselves are regenerated by the
  // creating action; this endpoint proves what was released and when, which is
  // the half that has to survive independently of the file.
  const manifest = [
    `# Steady export manifest ${id}`,
    `# Surface: ${row.surface}`,
    `# Cohort version: ${row.cohort_version}`,
    `# Filter hash: ${row.filter_hash}`,
    `# Filter: ${rebuilt?.filter_json ?? "{}"}`,
    `# Purpose: ${row.purpose}`,
    `# Rows: ${rebuilt?.row_count ?? 0}`,
    `# Suppressed cells: ${rebuilt?.suppressed_cells ?? 0}`,
    `# Content hash: ${row.content_hash}`,
    `# Signature verified: yes`,
    `# Released: ${row.created_at}`,
    `# FABRICATED DEMONSTRATION DATA — NOT CLINICAL OR FINANCIAL RECORD`,
  ].join("\n");

  return new NextResponse(`${manifest}\n`, {
    status: 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "content-disposition": `attachment; filename="steady-export-${id.slice(0, 8)}-manifest.txt"`,
      "cache-control": "no-store",
    },
  });
}
